@extends('layout.candidate.sidenav-layout')
@section('content')
    @include('components.dashboard.candidate.profile')
    @include('components.dashboard.candidate.social')
    @include('components.dashboard.candidate.education')
    @include('components.dashboard.candidate.training')
    @include('components.dashboard.candidate.experience')
    @include('components.dashboard.candidate.otherInfo')
@endsection
